// <auto-generated />
using System;
using Fundamentos.Elastic.Kibana.Serilog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fundamentos.Elastic.Kibana.Serilog.Migrations
{
    [DbContext(typeof(ElasticContext))]
    [Migration("20220211223732_alteracao")]
    partial class alteracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fundamentos.Elastic.Kibana.Serilog.Models.Publicacao", b =>
                {
                    b.Property<Guid>("PublicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("PublicacaoId");

                    b.ToTable("Publicacao");
                });
#pragma warning restore 612, 618
        }
    }
}
